spring.application.name=mma-gym
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.open-in-view=${SPRING_JPA_OPEN_IN_VIEW:false}
server.port=${SERVER_PORT}

spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:false}